import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/sass/global.scss";
import "../../public/sass/helper/base.scss";
import "../../public/sass/helper/helper.scss";
import "../../public/sass/helper/reset.scss";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin-ext"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} id="pb_scroll">
        {children}
      </body>
    </html>
  );
}
